#!/usr/bin/env python3

import requests
import json
from aci_token import get_token

def get_faults():
   token = get_token()
   url = "https://APIC-IP/api/node/class/faultInfo.json?query-target-filter=and(gt(faultInfo.created,%22YYYY-MM-DDTHH:MM:SS%22),lt(faultInfo.created,%22YYYY-MM-DDTHH:MM:SS%22))"
   headers = {
      "Cookie" : f"APIC-Cookie={token}", 
   }

   requests.packages.urllib3.disable_warnings()
   response = requests.get(url, headers=headers, verify=False)

   return response

if __name__ == "__main__":
    response = get_faults().json()
    fault_summary = response['imdata']
    fault_summary_json = json.dumps(fault_summary,indent=1)
    print(fault_summary_json)
    with open('fault_summary_json.json', 'w') as output:
        output.write(fault_summary_json)
    print("Done")
